Expand all runAtLocation methods to support chunk coordinate arguments
TechnicallyCoded/FoliaLib pull request #20
Opened 2024-06-23 19:37 UTC by xGinko

Closes #11

Adds support for passing in chunk and coordinates for all runAtLocation methods.

2024-06-25 00:09 UTC, CJCrafter commented
Hey xGinko, typically this developer likes to merge PRs into `dev`, not `main`. TechnicallyCoded handles all merges from `dev` into `main` then... Can you change the branch to `dev`?

2024-06-25 00:12 UTC, CJCrafter requested changes
These changes will be needed to match up with the `dev` branch.

2024-06-25 00:12 UTC, CJCrafter commented on platform/common/src/main/java/com/tcoded/folialib/impl/ServerImplementation.java
> +    void runAtLocationLater(World world, int chunkX, int chunkZ, @NotNull Consumer<WrappedTask> consumer, long delay);
This should return a `CompleteableFuture<Void>`, matching the other methods from #16

2024-06-25 00:12 UTC, CJCrafter commented on platform/common/src/main/java/com/tcoded/folialib/impl/ServerImplementation.java
> +    void runAtLocationLater(World world, int chunkX, int chunkZ, @NotNull Consumer<WrappedTask> consumer, long delay, TimeUnit unit);
This should return a `CompleteableFuture<Void>`, matching the other methods from #16

2024-06-25 18:55 UTC, xGinko commented
yo @CJCrafter thanks for pointing me in the right direction

2024-07-03 09:51 UTC, TechnicallyCoded requested changes

2024-07-03 10:01 UTC, TechnicallyCoded commented
Hey @xGinko , thank you for contributing! 

As you noticed, we requested a few changes, so there 2 main things that need changing before accepting this:
- If you can address these pointers we gave you directly in the code review
- Please move all the runAtChunk methods together instead of intertwined with the runAtLocation methods, the same way all the runAsync and runAtEntity are grouped together

2024-07-19 13:42 UTC, TechnicallyCoded commented
@xGinko Should we keep this open?

2024-07-23 15:42 UTC, xGinko commented
@TechnicallyCoded I'll make a new one

2024-07-23 15:42 UTC, closed without merging

2026-03-21 10:36 UTC, jquery-package commented
I was just about to implement methods like these. @xGinko are you still planning to submit a PR for this, or should I create my own?